name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images (dev)
        run: |
          docker-compose -f docker-compose.dev.yml build
          docker-compose -f docker-compose.dev.yml up -d
        env:
          DOCKER_BUILDKIT: 1

      - name: Run tests (dev)
        run: |
          # Здесь можно добавить команды для запуска тестов
          echo "Running tests in dev environment"

      - name: Build and push Docker images (prod)
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml up -d
        env:
          DOCKER_BUILDKIT: 1

      - name: Run tests (prod)
        run: |
          # Здесь можно добавить команды для запуска тестов
          echo "Running tests in prod environment"
