version: '3.8'

services:
  authorization:
    build: ./authorisation-service
    ports:
      - "8000:8000"
    env_file:
      - .env.dev

  music-streaming:
    build: ./music-streaming-service
    ports:
      - "8001:8001"
    env_file:
      - .env.dev

  admin:
    build: ./admin-service
    ports:
      - "8002:8002"
    env_file:
      - .env.dev

volumes:
  mysql_data:
